name: Go CI with Custom Action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run custom Go action
        uses: Dev-cmyser/workflows@main
