name: Go CI with Custom Action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Test GitHub Action Environment
        uses: actions/checkout@v3
