services:
  calc_ipoteca:
    restart: always
    container_name: calc_ipoteca_prod
    build:
      context: ../../
      dockerfile: docker/prod/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ../../.env
