// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// HttpSignalError is an autogenerated mock type for the HttpSignalError type
type HttpSignalError struct {
	mock.Mock
}

// Error provides a mock function with given fields:
func (_m *HttpSignalError) Error() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Error")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Status provides a mock function with given fields:
func (_m *HttpSignalError) Status() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// UnWrap provides a mock function with given fields:
func (_m *HttpSignalError) UnWrap() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for UnWrap")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewHttpSignalError creates a new instance of HttpSignalError. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHttpSignalError(t interface {
	mock.TestingT
	Cleanup(func())
}) *HttpSignalError {
	mock := &HttpSignalError{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
