definitions:
  entity.CachedMortgage:
    properties:
      aggregates:
        $ref: '#/definitions/mortgage.Aggregates'
      id:
        type: integer
      params:
        $ref: '#/definitions/mortgage.Params'
      program:
        $ref: '#/definitions/mortgage.Program'
    type: object
  entity.Mortgage:
    properties:
      aggregates:
        $ref: '#/definitions/mortgage.Aggregates'
      params:
        $ref: '#/definitions/mortgage.Params'
      program:
        $ref: '#/definitions/mortgage.Program'
    type: object
  mortgage.Aggregates:
    properties:
      last_payment_date:
        type: string
      loan_sum:
        type: integer
      monthly_payment:
        type: integer
      overpayment:
        type: integer
      rate:
        type: integer
    type: object
  mortgage.Params:
    properties:
      initial_payment:
        type: integer
      months:
        type: integer
      object_cost:
        type: integer
    type: object
  mortgage.Program:
    properties:
      base:
        type: boolean
      military:
        type: boolean
      salary:
        type: boolean
    type: object
  mortgage.Request:
    properties:
      initial_payment:
        type: integer
      months:
        type: integer
      object_cost:
        type: integer
      program:
        $ref: '#/definitions/mortgage.Program'
    type: object
  v1.executeResponse:
    properties:
      result:
        $ref: '#/definitions/entity.Mortgage'
    type: object
info:
  contact: {}
paths:
  /mortgage/cache:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.CachedMortgage'
            type: array
        "404":
          description: Not Found
          schema: {}
      summary: Get all cache
  /mortgage/execute:
    post:
      consumes:
      - application/json
      description: Calculates mortgage payments and provides a summary of the payment
        plan based on the input details and selected credit program.
      parameters:
      - description: Mortgage calculation request payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/mortgage.Request'
      produces:
      - application/json
      responses:
        "200":
          description: Successful mortgage calculation with loan details
          schema:
            $ref: '#/definitions/v1.executeResponse'
        "500":
          description: Internal server error
          schema: {}
      summary: Mortgage Calculation
      tags:
      - Mortgage
swagger: "2.0"
